# Generated by Django 5.2.7 on 2025-11-03 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pcb_type_app', '0003_assign_permissions_to_mng_pcb_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleConfigPcb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('pcb_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcb_type_app.pcbtype')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleConfigType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('pcbs', models.ManyToManyField(related_name='module_configs', through='module_config_type_app.ModuleConfigPcb', to='pcb_type_app.pcbtype')),
            ],
        ),
        migrations.AddField(
            model_name='moduleconfigpcb',
            name='module_config_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_config_type_app.moduleconfigtype'),
        ),
        migrations.AlterUniqueTogether(
            name='moduleconfigpcb',
            unique_together={('module_config_type', 'pcb_type')},
        ),
    ]
