# Generated by Django 5.2.7 on 2025-10-29 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_config_type_app', '0003_assign_permissions_to_mng_test_config_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frequencymeasurement',
            name='test_config',
        ),
        migrations.RemoveField(
            model_name='resistancemeasurement',
            name='test_config',
        ),
        migrations.RemoveField(
            model_name='voltagemeasurement',
            name='test_config',
        ),
        migrations.RemoveField(
            model_name='yesnoquestion',
            name='test_config',
        ),
        migrations.CreateModel(
            name='TestStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_type', models.CharField(choices=[('VOLTAGE', 'Voltage Measurement'), ('CURRENT', 'Current Measurement'), ('RESISTANCE', 'Resistance Measurement'), ('FREQUENCY', 'Frequency Measurement'), ('QUESTION', 'Yes/No Question'), ('INSTRUCTION', 'Instruction/User Action')], max_length=20)),
                ('order', models.PositiveIntegerField()),
                ('parameter_name', models.CharField(blank=True, max_length=100, null=True)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=10, null=True)),
                ('question_text', models.CharField(blank=True, max_length=500, null=True)),
                ('required_answer', models.BooleanField(default=True)),
                ('instruction_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='test_config_type_app.testconfigtype')),
            ],
            options={
                'verbose_name': 'Test Step',
                'verbose_name_plural': 'Test Steps',
                'ordering': ['test_config', 'order'],
            },
        ),
        migrations.DeleteModel(
            name='CurrentMeasurement',
        ),
        migrations.DeleteModel(
            name='FrequencyMeasurement',
        ),
        migrations.DeleteModel(
            name='ResistanceMeasurement',
        ),
        migrations.DeleteModel(
            name='VoltageMeasurement',
        ),
        migrations.DeleteModel(
            name='YesNoQuestion',
        ),
    ]
