# Generated by Django 5.2.7 on 2025-10-30 05:29

from django.db import migrations


def replace_omega_with_ohm(apps, schema_editor):
    """Replace Ω with ohm in the database"""
    TestStep = apps.get_model('test_config_type_app', 'TestStep')
    
    # Update all resistance measurements to use 'ohm' instead of 'Ω'
    resistance_steps = TestStep.objects.filter(unit='Ω')
    for step in resistance_steps:
        step.unit = 'ohm'
        step.save()


def reverse_replace_omega_with_ohm(apps, schema_editor):
    """Reverse the replacement of ohm with Ω"""
    TestStep = apps.get_model('test_config_type_app', 'TestStep')
    
    # Update all resistance measurements to use 'Ω' instead of 'ohm'
    resistance_steps = TestStep.objects.filter(unit='ohm')
    for step in resistance_steps:
        step.unit = 'Ω'
        step.save()


class Migration(migrations.Migration):

    dependencies = [
        ('test_config_type_app', '0004_remove_frequencymeasurement_test_config_and_more'),
    ]

    operations = [
        migrations.RunPython(replace_omega_with_ohm, reverse_replace_omega_with_ohm),
    ]
