# Generated by Django 5.2.7 on 2025-11-03 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('New', 'New'), ('ATP_1_Pending', 'ATP 1 Pending'), ('ATP_1_Complete', 'ATP 1 Complete'), ('ESS_Pending', 'ESS Pending'), ('ESS_Complete', 'ESS Complete'), ('ATP_2_Pending', 'ATP 2 Pending'), ('ATP_2_Complete', 'ATP 2 Complete'), ('Shipped', 'Shipped')], default='New', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ATPReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_phase', models.CharField(choices=[('ATP_1', 'ATP 1'), ('ATP_2', 'ATP 2')], max_length=5)),
                ('report_file', models.FileField(upload_to='atp_reports/')),
                ('qa_signoff', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('signed_off_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ESSReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_file', models.FileField(upload_to='ess_reports/')),
                ('qa_signoff', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('signed_off_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
