# Generated by Django 5.2.7 on 2025-11-03 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('module_app', '0001_initial'),
        ('module_config_type_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='module_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='module_config_type_app.moduleconfigtype'),
        ),
        migrations.AddField(
            model_name='essreport',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ess_reports', to='module_app.module'),
        ),
        migrations.AddField(
            model_name='atpreport',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atp_reports', to='module_app.module'),
        ),
    ]
