# Generated by Django 5.2.7 on 2025-11-04 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_app', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='atpreport',
            name='report_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='essreport',
            name='report_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='module',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='atpreport',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='atp_reports/'),
        ),
        migrations.AlterField(
            model_name='atpreport',
            name='signed_off_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atp_reports_signed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='essreport',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='ess_reports/'),
        ),
        migrations.AlterField(
            model_name='essreport',
            name='signed_off_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ess_reports_signed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('ATP_1_Pending', 'ATP 1 Pending'), ('ATP_1_In_Progress', 'ATP 1 In Progress'), ('ATP_1_Complete', 'ATP 1 Complete'), ('ESS_Pending', 'ESS Pending'), ('ESS_In_Progress', 'ESS In Progress'), ('ESS_Complete', 'ESS Complete'), ('ATP_2_Pending', 'ATP 2 Pending'), ('ATP_2_In_Progress', 'ATP 2 In Progress'), ('ATP_2_Complete', 'ATP 2 Complete'), ('Shipped', 'Shipped')], default='New', max_length=20),
        ),
    ]
