# Generated by Django 5.2.7 on 2025-10-30 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pcb_type_app', '0003_assign_permissions_to_mng_pcb_type'),
        ('test_config_type_app', '0005_replace_omega_with_ohm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('hardware_version', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pcb_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='pcb_type_app.pcbtype')),
                ('test_config_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='test_config_type_app.testconfigtype')),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batches',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Pcb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('hardware_modified', models.BooleanField(default=False)),
                ('modified_hardware_version', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pcbs', to='batch_app.batch')),
            ],
            options={
                'verbose_name': 'PCB',
                'verbose_name_plural': 'PCBs',
                'ordering': ['serial_number'],
            },
        ),
    ]
